### ISSUE TITLE
Cant load plugin

### ISSUE THREAD

**Issue by gonzague** [stenehall/homebridge-ikea#18]
Hi !
I get the following error when starting home bridge 👍 

`[9/13/2017, 12:47:38 PM] ====================
[9/13/2017, 12:47:38 PM] ERROR LOADING PLUGIN homebridge-ikea:
[9/13/2017, 12:47:38 PM] /usr/local/lib/node_modules/homebridge-ikea/index.js:49
  accessories: async function(callback) {
                     ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:65:22)
[9/13/2017, 12:47:38 PM] ====================
`

Any clue on how to fix this ? :( 

thanks

**Comment by danielkihlgren** [comment]
Updating node worked for me but after the update I had to fix another problem that was fixed by this link https://github.com/nfarina/homebridge/issues/905#issuecomment-274251797

**Comment by gonzague** [comment]
Thanks Daniel ! I ended up using this plugin https://github.com/jesper-lindberg/homebridge-tradfri
