### ISSUE TITLE
Plugin crashes on load

### ISSUE THREAD

**Issue by jsve** [stenehall/homebridge-ikea#20]
Oct 11 19:48:59 xxx yyy[816]: [10/11/2017, 7:48:59 PM] ERROR LOADING PLUGIN homebridge-ikea:
Oct 11 19:48:59 xxxx yyy[816]: [10/11/2017, 7:48:59 PM] /usr/local/lib/node_modules/homebridge-ikea/index.js:49
Oct 11 19:48:59 xxx yyy[816]: accessories: async function(callback) {
Oct 11 19:48:59 xxx yyy[816]: ^^^^^^^^
Oct 11 19:48:59 xxx yyy[816]: SyntaxError: Unexpected token function
Oct 11 19:48:59 xxx yyy[816]: at Object.exports.runInThisContext (vm.js:76:16)
Oct 11 19:48:59 xxx yyy[816]: at Module._compile (module.js:542:28)
Oct 11 19:48:59 xxx yyy[816]: at Object.Module._extensions..js (module.js:579:10)
Oct 11 19:48:59 xxx yyy[816]: at Module.load (module.js:487:32)
Oct 11 19:48:59 xxx yyy[816]: at tryModuleLoad (module.js:446:12)
Oct 11 19:48:59 xxx yyy[816]: at Function.Module._load (module.js:438:3)
Oct 11 19:48:59 xxx yyy[816]: at Module.require (module.js:497:17)
Oct 11 19:48:59 xxx yyy[816]: at require (internal/module.js:20:19)
Oct 11 19:48:59 xxx yyy[816]: at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:65:22)
Oct 11 19:48:59 xxx yyy[816]: at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:132:14)

**Comment by stenehall** [comment]
What version of node are you running? It looks like it's the `async` that crashes. That would mean you're running a to old version of node.

**Comment by jsve** [comment]
I’m on v6.9.5

Is that considered outdated? Having no problem with other plugins and scripts.

**Comment by stenehall** [comment]
Async was introduced in v7 I think. The latest stable release is v8.7.0. While LTS is still on 6.11.4. But since I wanted fancy async/await (it makes for so much cleaner code) you'd sadly have to upgrade for it to work.
